### ISSUE TITLE
page level styles

### ISSUE THREAD

**Issue by cjessett** [andyoliver3/prj-rev-bwfs-dasmoto#3]
(Simplify) [Here](https://github.com/andyoliver3/prj-rev-bwfs-dasmoto/blob/c8152a261af8e825bfd51321a665ad4ce124514f/Dasmoto's%20Arts/Resources/css/style.css#L2) you can just use the `body` selector and apply these properties to the `body` element. Then, all child elements of the `body` will inherit these properties.

**Comment by andyoliver3** [comment]
Thank You. I tried that first but for some reason the text didn't change. Must have been a formatting issue on my part. Just tried again and it works great.
